### ISSUE TITLE
Normalized growth?

### ISSUE THREAD

**Issue by thorsteinssonh** [bgautijonsson/covid19#3]
Hi, will write in English for everyone to understand and comment.
Im not much into reading R code, so I just wanted to ask.
Does the model take any account in nomalising the confirmed case numbers by the number measured, or does it simply rely on confirmed cases irrespective of sampling?

I can imagine that simply following case numbers could be OK - I have no experience with such modeling. Especially as the sampling is highly complex and correlated - so maybe some reason to ignore sampling and sampling methods.

However, when I look at the latest numbers on covid.is,  the confirmed case rate seems to be plateauing, maybe reaching 1200 cases if things start turning around now in next few days.

However the normalized growth rate is still growing significantly.  I.e. I mean the rate of confirmed cases divided by number measured in each batch.  This looks a little disconcerting to the untrained eye, maybe indicating a very bad outlook.

**Comment by bgautijonsson** [comment]
Thank you for the post, @thorsteinssonh! As you say, comparing case numbers between countries is problematic because of testing. Our stance, as written in the technical report, is:

_This model does not predict the total amount of COVID-19 cases, it predicts the total amount of DIAGNOSED COVID-19 cases. It then depends on each country’s specific diagnostic criteria what that number means. Iceland does many tests per capita so there it is predicting a broader spectrum of cases, not all serious, whereas in a country like Italy or Spain the model’s predictions have another meaning as the diagnostic criteria are different from those of Iceland._

Link to report: https://rpubs.com/bgautijonsson/HierarchicalLogisticGrowthCurves
